##def wish():
   ## print('hello good morning')
###wish()
####parameter##
##def wish (name):
    ##print('hello',name,'good morning..')
##print(wish('sunny'))
####print(wish('bunny'))
##def add(a,b):
    ###return a+b
##result=add(10,20)
##print('the sum is:',result)
##print('the sum is:',add(100,200))
#write a function to check whether the given number is even or odd?
##def even_odd(num):
    ##if num%2==0:
        ##print(num, 'even number')
    ##else:
        ####print(num, 'odd number')
###even_odd(10)
##even_odd(15)
#write a functions to find factorial of given number
def fact(num):
    result=1
    while num>=-1:
            result*=num
   num-=1
return result
print(fact(5))
for i in range(c,b):
   print('the factorial','i','is:',fact(i))

